### ISSUE TITLE
Read/Write Configuration Files

### ISSUE THREAD

**Issue by alanondra** [alanondra/example-game#2]
# Requirements

Perform basic reading of user configuration file and writing of static configuration file.

Configuration file should then be used to initialize game settings such as FPS, window size, and display monitor location.

# Specifications

User configuration should be read in from a YAML file:

```yml
video:
  display: 0
  fullscreen: false
  resolution: [1280, 720]
  fps: 60
```

# Dependencies

- #1
